### ISSUE TITLE
The deepFlow-server Unavailable

### ISSUE THREAD

**Issue by wanshaoyuan** [deepflowys/deepflow#700]
# Expected Behavior
The DeepFlow-server starts normally. Procedure
# Actual Behavior
The deepFlow-server Unavailable

# Steps to Reproduce the Problem

```
helm repo add deepflow https://deepflowys.github.io/deepflow
helm install deepflow -n deepflow deepflow/deepflow --create-namespace  --set server.readinessProbe.failureThreshold=135 --set server.livenessProbe.failureThreshold=135 
```
Environment：

OS：ubuntu:18.04
Kubernetes：1.20.15
CNI：Ciliumv1.12.1
deepFlow：v6.1.1

# Additional Info

-  deepflow version:v6.1.1

   **Output of `kubectl exec -it -n deepflow sts/deepflow-server -c deepflow-server -- deepflow-server -v`:**
  ```
  2022/08/25 23:28:13 /root/actions-runner2/_work/deepflow/deepflow/server/controller/trisolaris/dbmgr/dbmgr.go:145 record not found
[1.098ms] [rows:0] SELECT * FROM `host_device` WHERE `name` = 'rke-node3' AND `host_device`.`deleted_at` IS NULL ORDER BY `host_device`.`id` LIMIT 1
2022-08-25 23:28:13.761 [ERRO] [trisolaris/vtap] vtap_discovery.go:148 vtap(192.168.0.7-fa:16:3e:fe:18:e6) query host_device failed from host(rke-node3), err: record not found
2022-08-25 23:28:13.764 [ERRO] [trisolaris/vtap] vtap_discovery.go:302 vtap(192.168.0.7-fa:16:3e:fe:18:e6) vinterface_ip([192.168.0.7 172.17.0.1 10.0.0.89 192.168.0.7]) not found
2022-08-25 23:28:13.766 [ERRO] [trisolaris/vtap] vtap_discovery.go:320 vtap(192.168.0.7-fa:16:3e:fe:18:e6) ip_resource([192.168.0.7 172.17.0.1 10.0.0.89 192.168.0.7]) not found
2022-08-25 23:28:13.766 [INFO] [trisolaris/vtap] vtap.go:1045 end vtap register
2022-08-25 23:28:13.878 [INFO] [trisolaris/synchronize] ntp.go:37 request ntp proxcy from ip: 192.168.0.6
2022-08-25 23:28:14.856 [INFO] [trisolaris/synchronize] ntp.go:37 request ntp proxcy from ip: 192.168.0.7
[GIN] 2022/08/25 - 23:28:16 | 200 |     133.767µs |       10.0.1.53 | GET      "/v1/health/"
[GIN] 2022/08/25 - 23:28:18 | 200 |      91.332µs |       10.0.1.53 | GET      "/v1/health/"
2022-08-25 23:28:22.853 [WARN] [genesis] grpc_server.go:101 genesis sync received message with vtap_id 0 from 192.168.0.7
2022-08-25 23:28:22.856 [WARN] [genesis] grpc_server.go:101 genesis sync received message with vtap_id 0 from 192.168.0.7
2022-08-25 23:28:22.856 [INFO] [genesis] grpc_server.go:153 genesis sync received version 0 -> 1661440933 from ip 192.168.0.7 vtap_id 0
2022-08-25 23:28:23.389 [WARN] [genesis] grpc_server.go:101 genesis sync received message with vtap_id 0 from 192.168.0.6
2022-08-25 23:28:23.391 [WARN] [genesis] grpc_server.go:101 genesis sync received message with vtap_id 0 from 192.168.0.6
2022-08-25 23:28:23.391 [INFO] [genesis] grpc_server.go:153 genesis sync received version 0 -> 1661440993 from ip 192.168.0.6 vtap_id 0
2022-08-25 23:28:24.500 [WARN] [genesis] grpc_server.go:182 kubernetes api sync received message with vtap_id 0 from 192.168.0.6
2022-08-25 23:28:24.500 [INFO] [genesis] grpc_server.go:234 kubernetes api sync received version 1661440994 from ip 192.168.0.6 no vtap_id
2022-08-25 23:28:24.576 [WARN] [genesis] grpc_server.go:182 kubernetes api sync received message with vtap_id 0 from 192.168.0.6
2022-08-25 23:28:24.576 [INFO] [genesis] grpc_server.go:234 kubernetes api sync received version 1661440994 from ip 192.168.0.6 no vtap_id
[GIN] 2022/08/25 - 23:28:26 | 200 |     114.887µs |       10.0.1.53 | GET      "/v1/health/"
2022-08-25 23:28:26.669 [INFO] [droplet.syslog] elasticsearch.go:67 Syslog ESWriter connects to http://elasticsearch:20042
2022-08-25 23:28:31.957 [WARN] [droplet.syslog] elasticsearch.go:72 failed connecting to elasticsearch: health check timeout: Head "http://elasticsearch:20042": dial tcp: lookup elasticsearch on 10.43.0.10:53: no such host: no Elasticsearch node available
[GIN] 2022/08/25 - 23:28:36 | 200 |      76.716µs |       10.0.1.53 | GET      "/v1/health/"
[GIN] 2022/08/25 - 23:28:38 | 200 |      85.477µs |       10.0.1.53 | GET      "/v1/health/"
[GIN] 2022/08/25 - 23:28:46 | 200 |     107.132µs |       10.0.1.53 | GET      "/v1/health/"
2022-08-25 23:28:54.623 [INFO] [trisolaris/synchronize] tsdb.go:60 ctrl_ip is 192.168.0.6, (platform data version 1661441159 -> 1661441159), (acl version 3661441359 -> 0), (groups version 1661441159 -> 1661441159), NAME:roze-2
2022-08-25 23:28:54.623 [INFO] [trisolaris/synchronize] tsdb.go:60 ctrl_ip is 192.168.0.6, (platform data version 1661441159 -> 1661441159), (acl version 3661441359 -> 0), (groups version 1661441159 -> 1661441159), NAME:roze-3
2022-08-25 23:28:54.623 [INFO] [trisolaris/synchronize] tsdb.go:60 ctrl_ip is 192.168.0.6, (platform data version 1661441159 -> 1661441159), (acl version 3661441359 -> 0), (groups version 1661441159 -> 1661441159), NAME:roze
2022-08-25 23:28:54.626 [INFO] [trisolaris/synchronize] tsdb.go:71 ctrl_ip:192.168.0.6, cpu_num:8, memory_size:16818311168, arch:x86_64, os:alpine 3.16.2, kernel_version:4.15.0, pcap_data_mount_path:pcap_data_mount_path:"/"
2022-08-25 23:28:54.642 [INFO] [trisolaris/synchronize] tsdb.go:60 ctrl_ip is 192.168.0.6, (platform data version 1661441159 -> 1661441159), (acl version 3661441359 -> 0), (groups version 1661441159 -> 1661441159), NAME:roze-1
2022-08-25 23:28:55.201 [INFO] [trisolaris/synchronize] tsdb.go:60 ctrl_ip is 192.168.0.6, (platform data version 1661441159 -> 1661441159), (acl version 3661441359 -> 0), (groups version 1661441159 -> 1661441159), NAME:stream-open_telemetry-0
2022-08-25 23:28:55.203 [INFO] [trisolaris/synchronize] tsdb.go:60 ctrl_ip is 192.168.0.6, (platform data version 1661441159 -> 1661441159), (acl version 3661441359 -> 0), (groups version 1661441159 -> 1661441159), NAME:stream-l7-log-0
2022-08-25 23:28:55.208 [INFO] [trisolaris/synchronize] tsdb.go:60 ctrl_ip is 192.168.0.6, (platform data version 1661441159 -> 1661441159), (acl version 3661441359 -> 0), (groups version 1661441159 -> 1661441159), NAME:stream-open_telemetry-1
2022-08-25 23:28:55.208 [INFO] [trisolaris/synchronize] tsdb.go:60 ctrl_ip is 192.168.0.6, (platform data version 1661441159 -> 1661441159), (acl version 3661441359 -> 0), (groups version 1661441159 -> 1661441159), NAME:stream-l4-log-0
2022-08-25 23:28:55.209 [INFO] [trisolaris/synchronize] tsdb.go:60 ctrl_ip is 192.168.0.6, (platform data version 1661441159 -> 1661441159), (acl version 3661441359 -> 0), (groups version 1661441159 -> 1661441159), NAME:stream-l4-log-1
2022-08-25 23:28:55.215 [INFO] [trisolaris/synchronize] tsdb.go:60 ctrl_ip is 192.168.0.6, (platform data version 1661441159 -> 1661441159), (acl version 3661441359 -> 0), (groups version 1661441159 -> 1661441159), NAME:stream-l7-log-1
2022-08-25 23:28:55.453 [INFO] [trisolaris/synchronize] tsdb.go:60 ctrl_ip is 192.168.0.6, (platform data version 1661441159 -> 1661441159), (acl version 3661441359 -> 0), (groups version 1661441159 -> 1661441159), NAME:ext-metrics-telegraf-1
2022-08-25 23:28:55.453 [INFO] [trisolaris/synchronize] tsdb.go:60 ctrl_ip is 192.168.0.6, (platform data version 1661441159 -> 1661441159), (acl version 3661441359 -> 0), (groups version 1661441159 -> 1661441159), NAME:ext-metrics-prometheus-0
2022-08-25 23:28:55.457 [INFO] [trisolaris/synchronize] tsdb.go:60 ctrl_ip is 192.168.0.6, (platform data version 1661441159 -> 1661441159), (acl version 3661441359 -> 0), (groups version 1661441159 -> 1661441159), NAME:ext-metrics-telegraf-0
2022-08-25 23:28:55.462 [INFO] [trisolaris/synchronize] tsdb.go:60 ctrl_ip is 192.168.0.6, (platform data version 1661441159 -> 1661441159), (acl version 3661441359 -> 0), (groups version 1661441159 -> 1661441159), NAME:ext-metrics-prometheus-1
[GIN] 2022/08/25 - 23:28:56 | 200 |      63.128µs |       10.0.1.53 | GET      "/v1/health/"
[GIN] 2022/08/25 - 23:28:58 | 200 |      99.653µs |       10.0.1.53 | GET      "/v1/health/"
2022-08-25 23:28:59.008 [INFO] [cloud] cloud.go:155 cloud (k8s-d-9rDftkPt7B) assemble data starting
2022-08-25 23:28:59.008 [INFO] [cloud] kubernetes.go:34 domain (k8s-d-9rDftkPt7B) kubernetes_gather_task resource is null
2022-08-25 23:28:59.008 [INFO] [cloud] cloud.go:157 cloud (k8s-d-9rDftkPt7B) assemble data complete
2022-08-25 23:28:59.009 [INFO] [recorder] recorder.go:296 cloud domain (k8s-d-9rDftkPt7B) state info: 1,
2022-08-25 23:28:59.009 [INFO] [cloud] kubernetes_gather_task.go:86 kubernetes gather (k8s-d-9rDftkPt7B) assemble data starting
2022-08-25 23:28:59.020 [INFO] [monitor.license] pseudo_license.go:56 alloc license starting
2022-08-25 23:28:59.020 [INFO] [monitor] controller.go:72 controller health check start
2022-08-25 23:28:59.020 [INFO] [monitor] analyzer.go:71 analyzer health check start
2022-08-25 23:28:59.020 [INFO] [tagrecorder] tagrecorder.go:40 tagrecorder run
[GIN] 2022/08/25 - 23:28:59 | 200 |      94.822µs |       10.0.1.53 | GET      "/v1/health/"
2022-08-25 23:28:59.028 [INFO] [monitor] controller.go:141 controller health check end
[GIN] 2022/08/25 - 23:28:59 | 200 |      69.843µs |       10.0.1.53 | GET      "/v1/health/"
2022-08-25 23:28:59.030 [INFO] [monitor] controller.go:152 vtap controller check start
2022-08-25 23:28:59.030 [INFO] [monitor] analyzer.go:120 analyzer health check end
2022-08-25 23:28:59.030 [INFO] [monitor] analyzer.go:131 vtap analyzer check start
2022-08-25 23:28:59.032 [INFO] [monitor] analyzer.go:147 vtap analyzer check end
2022-08-25 23:28:59.032 [INFO] [monitor] analyzer.go:252 az connection check start
2022-08-25 23:28:59.033 [INFO] [monitor] controller.go:168 vtap controller check end
2022-08-25 23:28:59.033 [INFO] [monitor] controller.go:273 az connection check start
2022-08-25 23:28:59.034 [INFO] [tagrecorder] dictionary.go:79 refresh clickhouse dictionary in (192.168.0.6: 30900)
2022-08-25 23:28:59.035 [INFO] [monitor] analyzer.go:270 az connection check end
2022-08-25 23:28:59.036 [INFO] [monitor] controller.go:291 az connection check end
2022-08-25 23:28:59.041 [INFO] [monitor.license] pseudo_license.go:66 alloc license complete
2022-08-25 23:28:59.045 [INFO] [tagrecorder] dictionary.go:90 drop database deepflow
2022-08-25 23:28:59.049 [INFO] [recorder] recorder.go:121 domain (lcuuid: 1f87ac80-98a0-575f-9492-8f9c0641484b, name: k8s-d-9rDftkPt7B) has no networks or vinterfaces, does nothing
2022-08-25 23:28:59.061 [INFO] [cloud.kubernetes_gather] pod_service.go:106 service (deepflow-agent) target_port not match
2022-08-25 23:28:59.061 [INFO] [cloud.kubernetes_gather] pod_service.go:192 service (deepflow-agent) pod group not found
2022-08-25 23:28:59.062 [INFO] [cloud.kubernetes_gather] pod_service.go:106 service (metrics-server) target_port not match
2022-08-25 23:28:59.062 [INFO] [cloud.kubernetes_gather] pod_service.go:192 service (metrics-server) pod group not found
2022-08-25 23:28:59.063 [INFO] [cloud.kubernetes_gather] pod_service.go:68 service (kubernetes) selector not found
2022-08-25 23:28:59.063 [INFO] [cloud.kubernetes_gather] pod_service.go:192 service (deepflow-clickhouse-headless-0) pod group not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1d4c4a4]
goroutine 1596 [running]:
github.com/deepflowys/deepflow/server/controller/cloud/kubernetes_gather.(*KubernetesGather).getPodServices(0xc043d22420)
	/root/actions-runner2/_work/deepflow/deepflow/server/controller/cloud/kubernetes_gather/pod_service.go:137 +0x48c4
github.com/deepflowys/deepflow/server/controller/cloud/kubernetes_gather.(*KubernetesGather).GetKubernetesGatherData(_)
	/root/actions-runner2/_work/deepflow/deepflow/server/controller/cloud/kubernetes_gather/kubernetes_gather.go:267 +0x965
github.com/deepflowys/deepflow/server/controller/cloud.(*KubernetesGatherTask).Start.func1()
	/root/actions-runner2/_work/deepflow/deepflow/server/controller/cloud/kubernetes_gather_task.go:88 +0x1e8
created by github.com/deepflowys/deepflow/server/controller/cloud.(*KubernetesGatherTask).Start
	/root/actions-runner2/_work/deepflow/deepflow/server/controller/cloud/kubernetes_gather_task.go:79 +0x56

  ```
   **Output of `kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v`:**

  ```
2022-08-25 23:30:14.752152 +08:00] INFO [src/rpc/synchronizer.rs:1076] TapMode: Local, CtrlMac: fa:16:3e:fe:18:e6, CtrlIp: 192.168.0.7, Hostname: rke-node3
[2022-08-25 23:30:14.752617 +08:00] INFO [src/rpc/session.rs:313] rpc IP changed to controller 10.43.209.96 from unavailable controller 10.43.209.96
[2022-08-25 23:30:14.755711 +08:00] INFO [src/rpc/synchronizer.rs:1128] grpc sync new rpc server 10.43.209.96 available
[2022-08-25 23:30:24.899214 +08:00] INFO [src/rpc/session.rs:324] rpc IP changed to proxy 10.43.209.96 from controller 10.43.209.96
[2022-08-25 23:30:24.903672 +08:00] INFO [src/platform/platform_synchronizer.rs:622] local version 1661440933, remote version 0
[2022-08-25 23:31:24.913490 +08:00] INFO [src/platform/platform_synchronizer.rs:622] local version 1661440933, remote version 0
[2022-08-25 23:32:24.923016 +08:00] INFO [src/platform/platform_synchronizer.rs:622] local version 1661440933, remote version 0
[2022-08-25 23:33:15.806739 +08:00] ERROR [src/rpc/synchronizer.rs:1113] grpc sync error, server 10.43.209.96 unavailable, status-code Unknown error, message: "transport error"
[2022-08-25 23:33:17.278689 +08:00] WARN [src/rpc/synchronizer.rs:840] ntp request failed with: Status { code: Unknown, message: "transport error", source: None }
[2022-08-25 23:33:24.933050 +08:00] INFO [src/rpc/session.rs:304] rpc IP changed to controller 10.43.209.96 from unavailable proxy 10.43.209.96
[2022-08-25 23:33:25.950586 +08:00] ERROR [src/rpc/session.rs:142] dial server(10.43.209.96) failed transport error
[2022-08-25 23:33:26.974652 +08:00] ERROR [src/platform/platform_synchronizer.rs:629] send platform heartbeat failed: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
[2022-08-25 23:34:15.808815 +08:00] INFO [src/rpc/synchronizer.rs:1076] TapMode: Local, CtrlMac: fa:16:3e:fe:18:e6, CtrlIp: 192.168.0.7, Hostname: rke-node3
[2022-08-25 23:34:15.809233 +08:00] INFO [src/rpc/session.rs:313] rpc IP changed to controller 10.43.209.96 from unavailable controller 10.43.209.96
[2022-08-25 23:34:15.814702 +08:00] INFO [src/rpc/synchronizer.rs:1128] grpc sync new rpc server 10.43.209.96 available
[2022-08-25 23:34:26.979140 +08:00] INFO [src/rpc/session.rs:324] rpc IP changed to proxy 10.43.209.96 from controller 10.43.209.96
[2022-08-25 23:34:26.984170 +08:00] INFO [src/platform/platform_synchronizer.rs:622] local version 1661440933, remote version 0
[2022-08-25 23:35:26.997811 +08:00] INFO [src/platform/platform_synchronizer.rs:622] local version 1661440933, remote version 0
[2022-08-25 23:36:27.009644 +08:00] INFO [src/platform/platform_synchronizer.rs:622] local version 1661440933, remote version 0
[2022-08-25 23:37:16.862899 +08:00] ERROR [src/rpc/synchronizer.rs:1113] grpc sync error, server 10.43.209.96 unavailable, status-code Unknown error, message: "transport error"
[2022-08-25 23:37:18.526912 +08:00] WARN [src/rpc/synchronizer.rs:840] ntp request failed with: Status { code: Unknown, message: "transport error", source: None }
[2022-08-25 23:37:27.016681 +08:00] INFO [src/rpc/session.rs:304] rpc IP changed to controller 10.43.209.96 from unavailable proxy 10.43.209.96
[2022-08-25 23:37:28.034642 +08:00] ERROR [src/rpc/session.rs:142] dial server(10.43.209.96) failed transport error
[2022-08-25 23:37:29.054897 +08:00] ERROR [src/platform/platform_synchronizer.rs:629] send platform heartbeat failed: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
[2022-08-25 23:38:16.864445 +08:00] INFO [src/rpc/synchronizer.rs:1076] TapMode: Local, CtrlMac: fa:16:3e:fe:18:e6, CtrlIp: 192.168.0.7, Hostname: rke-node3
[2022-08-25 23:38:16.864856 +08:00] INFO [src/rpc/session.rs:313] rpc IP changed to controller 10.43.209.96 from unavailable controller 10.43.209.96
[2022-08-25 23:38:17.886636 +08:00] ERROR [src/rpc/session.rs:142] dial server(10.43.209.96) failed transport error
[2022-08-25 23:38:18.910795 +08:00] ERROR [src/rpc/synchronizer.rs:1113] grpc sync error, server 10.43.209.96 unavailable, status-code Unknown error, message: "transport error"
[2022-08-25 23:38:19.934680 +08:00] WARN [src/rpc/synchronizer.rs:840] ntp request failed with: Status { code: Unknown, message: "transport error", source: None }
[2022-08-25 23:38:29.060658 +08:00] INFO [src/rpc/session.rs:313] rpc IP changed to controller 10.43.209.96 from unavailable controller 10.43.209.96
[2022-08-25 23:38:30.078601 +08:00] ERROR [src/rpc/session.rs:142] dial server(10.43.209.96) failed transport error
[2022-08-25 23:38:31.102690 +08:00] ERROR [src/platform/platform_synchronizer.rs:629] send platform heartbeat failed: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  ```

- Kubernetes CNI: 

  ```
  Cilium1.12.1
  ```

- operation-system/kernel version:4.15.0-176-generic
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  
  **Output of `uname -r`:**
```
Ubuntu 18.04.5 LTS
4.15.0-176-generic
```

**Comment by mytting** [comment]
@wanshaoyuan  Does DeepFlow-Server fail to start?  Is Clickhouse ready? 

`kubectl get pod -n deepflow`

**Comment by wanshaoyuan** [comment]
@mytting 
```
kubectl get pod -n deepflow

NAME                               READY   STATUS    RESTARTS   AGE
deepflow-agent-4lg57               1/1     Running   5          14h
deepflow-agent-xbpqr               1/1     Running   4          14h
deepflow-app-6bb44bc749-m2bfb      1/1     Running   3          14h
deepflow-clickhouse-0              1/1     Running   3          14h
deepflow-grafana-589648c44-99x8g   1/1     Running   2          14h
deepflow-mysql-7fcd5cbfff-gnjtq    1/1     Running   3          14h
deepflow-server-0                  1/2     Running   111        14h
```
Does it depend on the operating system version and K8S version？

**Comment by mytting** [comment]
@wanshaoyuan 
`kubectl exec -it -n deepflow deploy/deepflow-mysql -- mysql -u root -pdeepflow -e "select * from deepflow.db_version;"`

**Comment by mytting** [comment]
@wanshaoyuan 
Try dropping DeepFlow Database and then restart DeepFlow-Server, the disk performance of this machine is not very good?

**Comment by wanshaoyuan** [comment]
> @wanshaoyuan Try dropping DeepFlow Database and then restart DeepFlow-Server, the disk performance of this machine is not very good?

Using a local disk and running ETCD, the performance seems to be OK

**Comment by mytting** [comment]
@wanshaoyuan  
Is it convenient to communicate with me on wechat? It's right at the bottom of Readme

**Comment by wanshaoyuan** [comment]
> @wanshaoyuan Is it convenient to communicate with me on wechat? It's right at the bottom of Readme

No problem, thank you

**Comment by mytting** [comment]
@SongZhen0704 kubernetes_gather panic
